version: '3.7'

services:
  api:
    container_name: 'desafio-lennon-api'
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - ${API_PORT}:${API_PORT}
      - ${API_DEBUG_PORT}:${API_DEBUG_PORT}
    command: npm run start:debug
    environment:
      DEBUG: "*"
      NODE_ENV: "development"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: 'desafio-lennon-mongo'
    volumes:
      - mongodb_desafio_lennon:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

volumes:
  mongodb_desafio_lennon: